language: node_js
node_js:
  - "7"
before_script:
    - npm install
script:
    - npm run lint
    - npm run test
    - npm run build
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c1f11e4065b90cd3bf33
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
